#!/bin/bash

echo "================================================"
echo "Docker镜像部署脚本"
echo "目标服务器: 60.205.160.74"
echo "================================================"
echo ""
echo "请手动执行以下步骤："
echo ""
echo "1. 连接到服务器："
echo "   ssh root@60.205.160.74"
echo "   密码: LOOK822621+1s"
echo ""
echo "2. 连接成功后，执行以下命令拉取镜像："
echo ""
echo "   # 拉取后端镜像"
echo "   docker pull lookfree/smartteacher-backend:latest"
echo ""
echo "   # 拉取教师端镜像"
echo "   docker pull lookfree/smartteacher-teacher-frontend:latest"
echo ""
echo "   # 拉取学生端镜像"
echo "   docker pull lookfree/smartteacher-student-frontend:latest"
echo ""
echo "3. 查看已拉取的镜像："
echo "   docker images | grep lookfree"
echo ""
echo "4. 或者一次性执行所有命令："
echo "   docker pull lookfree/smartteacher-backend:latest && \\"
echo "   docker pull lookfree/smartteacher-teacher-frontend:latest && \\"
echo "   docker pull lookfree/smartteacher-student-frontend:latest && \\"
echo "   docker images | grep lookfree"
echo ""
echo "================================================"